AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: support components event stream api

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD

Mappings:
  StageMap:
    CODE:
      DomainName: component-events-code.support.guardianapis.com
      CorsOrigin: "'*'"
    PROD:
      DomainName: component-events.support.guardianapis.com
      CorsOrigin: "'*'"

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Globals:

  EventStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: !Ref support-components-event-stream-${Stage}
      RetentionPeriodHours: 24
      ShardCount: 1

  Api:
    Cors:
      AllowOrigin: !FindInMap [ StageMap, !Ref Stage, CorsOrigin ]
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'*'"

Resources:
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: StreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:*
                Resource: !GetAtt EventStream.Arn

ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Ref AWS::StackName
        paths:

  BasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      RestApiId: !Ref ApiGateway
      DomainName: !Ref DomainName
      Stage: !Sub Prod
    DependsOn: ApiGatewayProdStage # auto generated by the Transform

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: support.guardianapis.com.
      Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      Comment: !Sub CNAME for contributions referrals endpoint ${Stage}
      Type: CNAME
      TTL: '120'
      ResourceRecords:
        - !GetAtt [ DomainName, RegionalDomainName ]

