AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: support component events stream api

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD
  CertificateArn:
    Description: ARN of the certificate
    Type: String

Mappings:
  StageMap:
    CODE:
      DomainName: component-events-code.support.guardianapis.com
      CorsOrigin: "'*'"
    PROD:
      DomainName: component-events.support.guardianapis.com
      CorsOrigin: "'*'"

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Globals:
  Api:
    Cors:
      AllowOrigin: !FindInMap [ StageMap, !Ref Stage, CorsOrigin ]
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'*'"

Resources:
  EpicViewEventStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub support-epic-view-event-stream-${Stage}
      RetentionPeriodHours: 24
      ShardCount: 1

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: StreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:*
                Resource: !GetAtt EpicViewEventStream.Arn

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Ref AWS::StackName
        paths:
          "/epic-view":
            "put":
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                credentials: !GetAtt ApiGatewayRole.Arn
                httpMethod: "POST"
                requestParameters:
                  "integration.request.header.Content-Type": "'application/x-amz-json-1.1'"
                requestTemplates:
                  application/json: !Sub "{\n    \"StreamName\": \"support-epic-view-event-stream-${Stage}\",\n    \"Records\": [\n{ \"Data\": \"$util.base64Encode($input.json('$'))\", \"PartitionKey\": \"1\"\n }\n]\n}"
                  application/x-amz-json-1.1: !Sub "{\n    \"StreamName\": \"support-epic-view-event-stream-${Stage}\",\n    \"Records\": [\n{ \"Data\": \"$util.base64Encode($input.json('$'))\", \"PartitionKey\": \"1\"\n }\n]\n}"
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      "application/json": "#set($inputRoot = $input.path('$'))"
                passthroughBehavior: when_no_match
                type: aws
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:kinesis:action/PutRecords"

  DomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      RegionalCertificateArn: # only for *.support.guardianapis.com
        !Ref CertificateArn
      DomainName: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      EndpointConfiguration:
        Types:
          - REGIONAL

  BasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      RestApiId: !Ref ApiGateway
      DomainName: !Ref DomainName
      Stage: !Sub Prod
    DependsOn: ApiGatewayProdStage # auto generated by the Transform

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: support.guardianapis.com.
      Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      Comment: !Sub CNAME for support component events stream API ${Stage}
      Type: CNAME
      TTL: '120'
      ResourceRecords:
        - !GetAtt [ DomainName, RegionalDomainName ]

