AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Super mode calculator state machine

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  App:
    Description: Application name
    Type: String
    Default: super-mode-calculator
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: membership-dist
  AthenaOutputBucket:
    Description: Name of the bucket to output athena query results to
    Type: String
    Default: gu-support-analytics
  AcquisitionEventsBucket:
    Description: Bucket containing the acquisition events data to be queried
    Type: String
    Default: acquisition-events
  SchemaName:
    Description: The schema name for the query
    Type: String
    Default: acquisition
  CronExpression:
    Description: Cron expression for scheduling the step functions
    Type: String
    Default: 00 * * * ? *
  ScheduleState:
    Description: The state of the schedule
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED

Conditions:
  IsProd: !Equals [!Ref "Stage", "PROD"]

Resources:
  PartitionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub super-mode-calculator-partition-lambda-${Stage}
      Description: Creates Athena paritions for querying epic views and acquisitions
      Runtime: nodejs14.x
      Handler: lambdas/partition/lambda.handler
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
          AthenaOutputBucket: !Ref AthenaOutputBucket
          SchemaName: !Ref SchemaName
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - Statement:
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3::*:${AthenaOutputBucket}/*"
              - !Sub "arn:aws:s3::*:${AthenaOutputBucket}"
        - Statement:
            Effect: Allow
            Action: s3:GetObject
            Resource:
              - arn:aws:s3::*:membership-dist/*

  QueryLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub super-mode-calculator-query-lambda-${Stage}
      Description: Queries Athena for article epic views and acquisitions
      Runtime: nodejs14.x
      Handler: lambdas/query/lambda.handler
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
          AthenaOutputBucket: !Ref AthenaOutputBucket
          SchemaName: !Ref SchemaName
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - Statement:
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3::*:${AthenaOutputBucket}/*"
              - !Sub "arn:aws:s3::*:${AthenaOutputBucket}"
        - Statement:
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3::*:${AcquisitionEventsBucket}/*"
              - !Sub "arn:aws:s3::*:${AcquisitionEventsBucket}"
        - Statement:
            Effect: Allow
            Action: s3:GetObject
            Resource:
              - arn:aws:s3::*:membership-dist/*

  CalculateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub super-mode-calculator-calculate-lambda-${Stage}
      Description: Calculates the list of articles that are in super mode
      Runtime: nodejs14.x
      Handler: lambdas/calculate/lambda.handler
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - Statement:
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3::*:${AthenaOutputBucket}/*"
              - !Sub "arn:aws:s3::*:${AthenaOutputBucket}"
        - Statement:
            Effect: Allow
            Action: s3:GetObject
            Resource:
              - arn:aws:s3::*:membership-dist/*
        - Statement:
            Effect: Allow
            Action: dynamodb:*
            Resource:
              - !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/super-mode-${Stage}
              - !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/super-mode-${Stage}/index/*

  StateMachineExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: "*"

  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    DependsOn:
      - QueryLambda
      - CalculateLambda
    Properties:
      StateMachineName:
        !Sub ${App}-${Stage}
      DefinitionString:
        !Sub
          - |
            {
              "Comment": "super-mode-calculator",
              "StartAt": "Partition",
              "States": {
                "Partition": {
                  "Type": "Task",
                  "Resource": "${PartitionLambdaArn}",
                  "Next": "Query"
                },
                "Query": {
                  "Type": "Task",
                  "Resource": "${QueryLambdaArn}",
                  "Next": "Calculate",
                  "Retry": [{
                    "ErrorEquals": ["QueryPendingError"],
                    "IntervalSeconds": 10,
                    "MaxAttempts": 5
                  }]
                },
                "Calculate": {
                  "Type": "Task",
                  "Resource": "${CalculateLambdaArn}",
                  "End": true,
                  "Retry": [{
                    "ErrorEquals": ["QueryPendingError"],
                    "IntervalSeconds": 10,
                    "MaxAttempts": 5
                  }]
                }
              }
            }
          -
            PartitionLambdaArn: !GetAtt PartitionLambda.Arn
            QueryLambdaArn: !GetAtt QueryLambda.Arn
            CalculateLambdaArn: !GetAtt CalculateLambda.Arn
      RoleArn: !GetAtt StateMachineExecutionRole.Arn

  TriggerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource: !Ref StateMachine

  Schedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub super-mode-calculator-schedule-${Stage}
      ScheduleExpression: !Sub cron(${CronExpression})
      State: !Ref ScheduleState
      Targets:
        - Arn: !Ref StateMachine
          RoleArn: !GetAtt TriggerExecutionRole.Arn
          Id: !GetAtt StateMachine.Name

  ExecutionFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmActions:
      - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarms-handler-topic-${Stage}
      AlarmName: !Sub ${App}-failed-${Stage}
      AlarmDescription: !Sub Super Mode calculation failed
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref StateMachine
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 900
      EvaluationPeriods: 1
      Statistic: Sum

