AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kinesis stream for epic view events'

Parameters:
  App:
    Description: Application name
    Type: String
    Default: epic-views-firehose
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  OutputBucketName:
    Description: Name of the s3 bucket to output data to
    Type: String
  KinesisARN:
    Description: ARN of the kinesis stream
    Type: String

Resources:
  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: firehose.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: firehose-s3-output-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${OutputBucketName}"
                  - !Sub "arn:aws:s3:::${OutputBucketName}/*"
        - PolicyName: firehose-kinesis-get
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:DescribeStream
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                Resource:
                  - !Ref KinesisARN
        - PolicyName: cloudwatch-logs-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:*"

  Firehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "epic-views-firehose-${Stage}"
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !Ref KinesisARN
        RoleARN: !GetAtt FirehoseRole.Arn
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:aws:s3:::${OutputBucketName}"
        Prefix: !Sub "epic-views/${Stage}/"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 10
        CompressionFormat: UNCOMPRESSED
        RoleARN: !GetAtt FirehoseRole.Arn